:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:

# 環境設定

== 現在のシェルを確認
[source,shell]
----
# 現在のシェルを確認
$ echo $SHELL
OR
$ printenv SHELL
----

== 非ログインシェルを終了

[source,shell]
----
$ exit
----

== 使用できるシェルの種類を確認
[source,shell]
.例
----
cat /etc/shells
----

== ログインシェル自体の変更
[source,shell]
.例
----
which zsh
## /bin/zsh

chsh -s /bin/zsh
----



== 自分のユーザー名を表示

[source,shell]
----
# 自分のユーザー名を表示
whoami
----

== sudo
* `sudo <実行したいコマンド>`
* sudoを実行するユーザーのパスワードが必要

== シェルスクリプト
実行したいコマンドを事前にファイルに記述したファイル

=== source
* ファイルに書かれたコマンドを現在のシェルで実行する
* `.` と `source` は、どちらも同じ意味と効果を持ちます。

[source,shell]
.例
----
source ~/.zshrc
----

=== exec -l $SHELL
* exec "$SHELL" -l の意味は、ログインシェル ($SHELL)をログインシェルとして起動するオプション (-l) 付きで起動し、現在のシェルを新しいシェルに入れ替える (exec) という意味です。これによってシェル本来の設定処理が行われます。

* 環境変数 ``$SHELL`` に書いてあるコマンドをログイン時の動作の様に実行して現在のシェルにプロセスが置き換わります。

* 現在実行中のシェルに代わり、指定したコマンドを実行する

* 例えば、シェルスクリプト等で、あるコマンドを実行する場合、プロセス上では、実行したいコマンドが終わるまでそのコマンドを実行するシェルスクリプトのプロセスが残ることになります。実行できるプロセス数には限界があり、execコマンドで実行すると無駄にプロセスが実行することを防げます。


* まず、環境変数 ``$SHELL`` が、/bin/zsh でないと別のシェルに変わります。
* また、ログイン時の動作なので、`~/.profile` も実行します。


=== #!/usr/bin/env (language)
shebang(シバン)::
* シェルスクリプトの1行目に書く「#!/bin/sh」とかのこと
* #! の後にスペースを入れても入れなくても構いませんが、どちらかといえば入れません。


Linux環境である言語のスクリプトを実行する場合、
エラーが出る可能性を低くするために、スクリプトの1行目書いておくと良い

シバンを #!/usr/bin/env (language) としてenvコマンドを使用することで、
PATH環境変数の通っている場所から言語のインタープリタが検索されます。

例えば、pythonスクリプトの場合を比較してみます。

`#!/usr/bin/python` と記載した場合::
pythonのインストールパスが #!/usr/local/bin/python だった場合にエラーとなる
virtualenvなどの仮想環境で使用されるpythonパスではないため、仮想環境にてスクリプトを実行できない

`#!/usr/bin/env python` と記載した場合::
* ``PATH環境変数``にpythonコマンドが通っていれば使用できる
* 汎用性・システム間の移植性が高い
virtualenvなどの仮想環境上でも使用できる(仮想環境起動時にPATHがうわがかれ)

後者の方がメリットが大きいことは明らかです。

.例
----
#!/usr/bin/env sh
#!/usr/bin/env ruby
#!/usr/bin/env python
----



== 環境変数
=== env

[source,shell]
.例
----
# 引数なしで実行すると、現在指定されている環境変数を一覧表示(= printenvコマンド)
env

# 環境変数を一時的に設定してコマンドを実行する
# env 環境変数名=値 コマンド
# 環境変数LANGに「C」を設定した状態でdateコマンドを実行
env LANG=C date
----

=== 環境変数の確認

[source,shell]
.printenvで確認
----
$ export hensu="melon"

$ printenv | grep hensu
hensu=melon
----

=== 環境変数PATHとは

==== https://reffect.co.jp/windows/full_understanding_mac[なぜpwdコマンドが実行できるのか]
[source,shell]
----
 % pwd
/Users/mac
----

* コマンドには必ずコマンド名と同じ名前のファイルが存在します。
* しかし、lsコマンドを実行しても現在いるディレクトリにはpwdの実行ファイル（pwdと同じ名前のファイル）はありません。

* では、pwdの実行ファイルはどこにあるのでしょうか？

[source,shell]
----
# whichはコマンドがどこにあるのかを教えてくれるコマンド
 % which pwd 
 /bin/pwd
----
* なぜbinの下にあるpwdコマンドを別のディレクトリから実行できるのでしょうか

[source,shell]
.環境変数を一覧表示
----
 % printenv
(...略)
 PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
(...略)
----
* このPATHの設定値の中にpwdの実行ファイルが存在した/binディレクトリがあることが確認できます!!
* `echo $PATH | tr ':' '\n'` でPATHだけ表示できます(これは整形表示)
* 先ほど実行したpwdコマンドは/binの下にあったことを思い出してください。環境変数PATHがこの情報を持っているからこそ/binディレクトリに存在するpwdコマンドが実行できるのです。

> 環境変数PATHの力を借りてpwdコマンドが実行される

=== echo $PATH
PATHを見やすく整形表示する方法

1. ターミナルを起動してpwdコマンドを実行
2. 環境PATHの中身を確認(/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin)
 先頭に記述されているディレクトリから順番にそのディレクトリ下にpwdの実行ファイルがあるかを確認していきます。
3. 最初に環境変数PATHの先頭に表示されている/usr/local/binの下にpwdの実行ファイルがあるか確認します。存在しない場合は、次に記述されているディレクトリを確認します。
4. /usr/binの下にpwdの実行ファイルがあるか確認するが存在しない場合は、次に記述されているディレクトリを確認します。
5. /binの下にpwdの実行ファイルがあるか確認し、pwdコマンドが存在することを確認。
6. /binが存在することが確認できたのでようやくpwdの実行ファイルを実行することができます。

[source,shell]
----
# これだとちょっと見にくいので
echo $PATH

# 整形表示する
echo $PATH | tr ':' '\n'

# 毎回このコマンドを打つのも面倒なので、aliasを設定してしまうのも手です。
$ alias mypath='echo $PATH | tr ":" "\n"'

$ mypath
----



=== export
* 環境変数を設定するためのコマンド
* export <シェル変数名>

[source,shell]
----
# 設定されている環境変数を表示
# envコマンドと同じようなもの
export -p
----

[source,shell]
.例
----
# 環境変数$ULBを設定
export ULB=/usr/local/bin

#どちらのコマンドでも同じ結果が出力される。
ls /usr/local/bin
ls $ULB

# 環境変数を削除
unset ULB #[$]は入力しなくて良い。
echo $ULB
#何も出力されない。
----


例: 3つのシェルファイルを用意します。`A.sh` 、`B.sh` 、 `C.sh` です。 +
B.shとC.shは、A.shで定義した変数の値を出力しようと試みます。

[source,shell]
.A.sh
----
export hensu="Apple"
----
* exportコマンドで環境変数を定義してあるだけのシェル


[source,shell]
.B.sh
----
#!/bin/bash

source A.sh
echo "A.shの変数の値(B.sh)："${hensu}
./C.sh
----
* sourceコマンドでA.shを実行した後、 C.shを実行

[source,shell]
.C.sh
----
#!/bin/bash

echo "A.shの変数の値(C.sh)："${hensu}
----

[source,shell]
.結果
----
$ ./B.sh
A.shの変数の値(B.sh)：Apple
A.shの変数の値(C.sh)：Apple
----

=== export PATH=$PATH:追加したいコマンド検索パス
* 環境変数$PATHを上書き(再設定)している記述

[source,shell]
.例
----
#現在$PATHに設定されているコマンド検索パスが以下の場合
#/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
#どちらの記述でも$PATHに設定されるコマンド検索パスは同じ。
export PATH=$PATH:追加したいコマンド検索パス
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:追加したいコマンド検索パス
----

== .zshrcファイル
[source,shell]
.cat /Users/xxxx/.zshrc
----
. /opt/homebrew/opt/asdf/libexec/asdf.sh

export PATH="$PYENV_ROOT/bin:$PATH"

# ターミナルでコマンド履歴の入力補完で便利なやつ
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh


# 補完
autoload -Uz compinit
compinit

# コマンドのスペルを訂正する
setopt correct

# エイリアス
alias so='source'

# git のカラー表示
git config --global color.ui auto

# 補完で小文字でも大文字にマッチさせる
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

# 色を使用
autoload -Uz colors
colors

# プロンプトを2行で表示、時刻を表示
PROMPT="%(?.%{${fg[green]}%}.%{${fg[red]}%})%n${reset_color}@${fg[blue]}%m${reset_color}(%*%) %~
%# "

# 重複するコマンド行は古い方を削除します。
setopt hist_ignore_all_dups
----